### ISSUE TITLE
New plugdj

### ISSUE THREAD

**Issue by Snowcrash5** [plugCubed/plugAPI#102]
How to make this work with the new plugDJ at stg.plug.dj?

**Comment by Moutard3** [comment]
Either wait for an update of PlugApi or edit plugapi like that:
client.js

Line 9:
`baseUrl: 'https://stg.plug.dj'`

Line 707:
```
ws = new WebSocket('wss://gostagedj.plug.dj:443/socket', {
    origin: 'https://stg.plug.dj'
});
```
