### ISSUE TITLE
Function for Switching Rooms?

### ISSUE THREAD

**Issue by TehTotalPwnage** [plugCubed/plugAPI#110]
I've looked through the wiki, and I can't seem to find a function that allows a bot to join a different room. Running 

`bot.connect(roomID)` 

a second time just returns a 400 - Bad Request error. I think it would make sense if such a function existed to be able to switch rooms, or at least if the existing connect function allowed for it.

**Comment by thedark1337** [comment]
The wiki is quite out of date and I haven't had the time to update it, `bot.changeRoom (roomSlug)`  is the function you are looking for  https://github.com/plugCubed/plugAPI/blob/master/lib/client.js#L1383-L1385

**Comment by TehTotalPwnage** [comment]
Okay cool, thanks. Seems the wiki is a little hard to navigate, if I can figure out more of the code, I might help in contributing to the wiki a little bit.
