### ISSUE TITLE
DJ Joining/Leaving [Add To Wiki]

### ISSUE THREAD

**Issue by SnazzyPine25** [plugCubed/plugAPI#112]

**Comment by thedark1337** [comment]
Are you asking what the event is for the waitlist updating? It would be `PlugAPI.events.DJ_LIST_UPDATE` 

If you're asking about how to join / leave with the bot it would be `bot.joinBooth()` and `bot.leaveBooth()`

**Comment by SnazzyPine25** [comment]
I wanted support to join and leave the booth

**Comment by thedark1337** [comment]
For your bot or for another user?

**Comment by SnazzyPine25** [comment]
For my bot.

**Comment by thedark1337** [comment]
```
 // Adding bot to waitlist
bot.joinBooth()

// Removing bot from waitlist
bot.leaveBooth()
```

**Comment by SnazzyPine25** [comment]
You should update that on the wiki.

**Comment by Dazzuh** [comment]
https://github.com/plugCubed/plugAPI/wiki/[actions]%20joinBooth
https://github.com/plugCubed/plugAPI/wiki/[actions]%20leaveBooth

added
