### ISSUE TITLE
My code runs a command when not told to.

### ISSUE THREAD

**Issue by spongecattle** [plugCubed/plugAPI#114]
bot.on('roomJoin', function(room) {
            console.log("Joined " + room);
            bot.sendChat('cBpt is here');
        });

        bot.on('chat', function(data) {
 			if (data.raw.message = '!test')
  				bot.sendChat('testing 123');
  			else
  				console.log('no command')
 		});

Expected:
cBpt
cBpt is here

ChocolateRain2
!test

cBpt
testing 123

Reality:
cBpt
cBpt is here
testing 123
testing 123
testing 123
testing 123
testing 123

why is this? can you help me
write a comment with fixed code or contact me at my plug.dj community http://plug.dj/chocolaterain2

**Comment by JTBrinkmann** [comment]
For those reading this and wondering, sponge messed up the comparison. In `if (data.raw.message = '!test')`, it should be `===` or `==` instead of just `=`.

**Comment by thedark1337** [comment]
I assume you've fixed the issue already as you've closed it, but yes, it should be `==` or `===` as @JTBrinkmann said. 
 
There is a more helpful way to write commands built into plugAPI that hasn't been documented at all that would be very useful to use.

For example:

```
bot.on('command:ping', function(data) {
   data.respond('pong!');
});
```
More info can be found at the source code here: https://github.com/plugCubed/plugAPI/blob/master/lib/client.js#L628-L753
