### ISSUE TITLE
Add a callback to bot.getMedia()

### ISSUE THREAD

**Issue by TheConceptionist** [plugCubed/plugAPI#118]
While I don't know about others, I use this API in combination with other Node packages. Trying to figure out how to use getMedia by itself is confusing enough, but trying to make it work with other things is a pain. Callbacks would help immensely.

**Comment by thedark1337** [comment]
Apologies for the late reply, time is not something I have atm due to school. [This](https://github.com/plugCubed/plugAPI/wiki/%5Bactions%5D%20getMedia) is the documentation for `bot.getMedia()`, but I can also add a callback if that's helpful to your usecase.

**Comment by Hunchmun** [comment]
Can I enquire what your use case is for adding callbacks to this method? It seems rather unnecessary to me...

**Comment by TheConceptionist** [comment]
> thedark1337 commented 3 days ago
Apologies for the late reply, time is not something I have atm due to school. This is the documentation for bot.getMedia(), but I can also add a callback if that's helpful to your usecase.

That'd be hecka helpful. Promises work too.

> Hunchmun commented 3 days ago
Can I enquire what your use case is for adding callbacks to this method? It seems rather unnecessary to me...

Yeah, sure. I use this in conjunction with discord.js. I'm trying to make my Discord bot retrieve the current song from a room, and post it into a Discord server. So far, I've had no luck. It may just be me being stupid (I'm kinda sucky with Node and JS in general), but callbacks help immensely.

**Comment by thedark1337** [comment]
if you want promises you could just use [Bluebird](https://npmjs.com/package/bluebird) and promisify plugAPI. As for how to use getMedia it'd be something like

```js
var media = bot.getMedia();
// use the media object now (such as for author, media.author, title is media.title. etc.
```
Example Media object: 
```js
{
    author: 'Freefire',
    cid: 'xxxxxxxx',
    duration: 333,
    format: 'x',
    id: 'xxxxxxxxxx',
    image: 'http://i.ytimg.com/vi/kT3vXUZ4TWc/default.jpg',
    title: 'Dataloss (Darth & Vader Remix)'
}
```

**Comment by Talos51** [comment]
In addition to thedark1337's answer, can't this piece of code do what you want?

The following code will return the current song of your Plug.DJ account whenever a user will send "!song" in the Discord chat ( but you can trigger the action on others events like song change, skip, etc... ).

```Javascript
// Client = Discord.js bot // bot = PlugDJ.API bot

// create an event listener for messages on Discord.js library
client.on('message', message => {
  // if the message is !song,
  if (message.content === "!song") {
    // Retrieve song information from PlugDJ.API
    var media = bot.getMedia();
    // send the current song
    message.reply("The current song on Plug.DJ room is: " + media.title + " from " + media.author);
  }
});
```

**Comment by TheConceptionist** [comment]
@Talos51 I thought I had tried that, but it turns out to work. Sorry about me being stupid. Closing issue.

**Comment by Talos51** [comment]
Thanks for your return, i'm glad that i was able to help you ^^ I let an admin close the ticket :)
