### ISSUE TITLE
SordBot

### ISSUE THREAD

**Issue by Sorduin** [plugCubed/plugAPI#120]
I use a simple API bot in my room https://plug.dj/ultimatescape-remastered

Bot is called SordBot. Room = US DJ ROOM

**Comment by YourturnGaming** [comment]
Ok, and is there something we can help you with?

**Comment by Sorduin** [comment]
http://prntscr.com/cv299d

**Comment by avatarkava** [comment]
Think he's just looking to have it added to the implementation list on the readme.
