### ISSUE TITLE
Add song from YouTube

### ISSUE THREAD

**Issue by WacMan** [plugCubed/plugAPI#126]
Hi,
How can I add a song from a YouTube link? I looked at the addSongToPlaylist action but it only takes a songID number argument. If I can't get this to work, my bot project won't work. :'(
Thanks,
WacMan

**Comment by TheBanHammer** [comment]
Hi there!

The songID argument can be taken from the Youtube Video URL. For example the songid for: `https://www.youtube.com/watch?v=9YrWsmlJSiw` is `9YrWsmlJSiw`.

The songID is the part after `?v=`

Hope this helps!

**Comment by WacMan** [comment]
Sweet!! I was afraid my dreams were crushed. Thanks for this awesome API!

And thanks for the blazing fast response.

**Comment by WacMan** [comment]
Hi again,

So I got my bot to where it should be able to add a song to a playlist, but I'm getting an error:
21 Mar 23:18:09 [ERROR]    [plugAPI]  [REST Error]  HTTP Status: 405 - Method No
t Allowed

I know that the playlist ID and song ID (from YouTube) are both correct.

Any idea?
Thanks!

**Comment by Benchmaker** [comment]
@WacMan just make a grab command make the bot preselected playlist and the code would be 

bot.on('command:grab', (data) => {
Plugapi rank here
bot.grab
}
};

**Comment by Benchmaker** [comment]
Its bot.grab();

Whoops and cheers!

**Comment by thedark1337** [comment]
@Benchmaker they're asking about adding a song from youtube not grabbing the current song. One of the devs will take a look at it and respond back if its an issue with how we handle the API route.

**Comment by thedark1337** [comment]
Ok so, for `bot.addSongToPlaylist` it takes a full media object

```js
bot.addSongToPlaylist(playlistid, {
   author: 'Three Days Grace' // song author,
   cid: 'U8ai37gFvMk' // the part https://youtube.com/watch?v=,
   duration: 182, // time in seconds of how long the song is
   format: 1, // 1 for youtube, 2 for soundcloud
   image: 'https://i.ytimg.com/vi/U8ai37gFvMk/default.jpg', // the thumbnail image link for the video.
   title: 'Painkiller' // song title
});
```

Not the most user friendly but when working with a backend API Route this is how it works. For multiple media items it would be an Array of Objects.

**Comment by WacMan** [comment]
@thedark1337 thanks for the reply. I tried what you said but I'm still getting the same error.

Also, where do you get that info regarding the function's signature? I looked at client.js in plugAPI but only found the variable is being forwarded to REST (which I assume is some sort of interface for the official plug.dj API). I also looked at the doc for the official plug.dj API but it seemed very limited and couldn't find anything.

**Comment by jFar920** [comment]
I hate to bump this after over a year, but I'm having trouble finding a solution since I am also getting the 405 error. I am able to do this through the console using the official endpoints, and I even copied @thedark1337's example just as a test and it didn't help
