### ISSUE TITLE
How can i find media's URL

### ISSUE THREAD

**Issue by btx78000** [plugCubed/plugAPI#130]
Hi guys, i am looking for a method for fetch media ( youtube & soundcloud ) URL with plugAPI for my music bot.

Nothing in getMedia, getHistory, and others method so if someone have an idea :P

Thanks

**Comment by dh111** [comment]
As in you want to add media to your bots playlist from the code, or you are trying to get the media links from the current playing song/history songs? @btx78000

**Comment by thedark1337** [comment]
Hi, there isn't an object property for a link to the current media. However you can write a command such as:

```js
bot.on('command:medialink', (data) => {
    const media = bot.getMedia();
    if (media == null) return;
    let link = '';

    if (media.format === 1) {
        link = `https://youtube.com/watch?v=${media.cid}`;
    } else if (media.format === 2) {
        link = `https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/${media.cid}`;
    }
    data.respond(link);
});
```

Which will return the youtube or soundcloud link you are needing.

**Comment by thedark1337** [comment]
However, if you want to play music from plug onto Discord.. @Dazzuh did write a bot as an example https://github.com/Dazzuh/plugdj-discord 

The only issue i know so far is that the Discord API that he is using has an issue with the stream suddenly stopping sometimes.

**Comment by btx78000** [comment]
It's not for discord bot so don't worry :p, i'll try ur code, u rock :O so fast ahah, thanks so much guy's
