### ISSUE TITLE
Should treat URLs as atoms when splitting long chat messages

### ISSUE THREAD

**Issue by mortenn** [plugCubed/plugAPI#143]
Sometimes, a bot chat message is too long so it gets split up.
This is a nice feature, but it can corrupt links.

It would be very much appreciated if the string splitter did some basic parsing to avoid this happening.

**Comment by mortenn** [comment]
Splits can also occur in the middle of a multibyte char, munging things like japanese and korean.

**Comment by mortenn** [comment]
![Example image](https://cdn.discordapp.com/attachments/86856250469392384/205980562895142914/unknown.png)

**Comment by thedark1337** [comment]
Have been planning to use https://www.npmjs.com/package/plug-message-split
for this exact purpose but haven't had time

**Comment by mortenn** [comment]
In the interim, I added that module to my own code. Was happy to see it has no deps :)

**Comment by thedark1337** [comment]
v5.1.0 has added this. Thanks @goto-bus-stop for creating plug-message-split <3
