### ISSUE TITLE
The advance event when last DJ finishes has djs.length == 2

### ISSUE THREAD

**Issue by mortenn** [plugCubed/plugAPI#145]
I've seen this over a long period of time. Not sure what djs contain, but I turned on some logging so I can get a dump of the property once it happens again.

**Comment by mortenn** [comment]
Got it; the djs array contains the bot's user object twice.

**Comment by thedark1337** [comment]
I see the issue. Its with room.usersToArray and room.getUser. When having an empty waitlist / no DJ it will have a null currentDJ and that triggers getUser to call getSelf. Will look into a workaround with that
