### ISSUE TITLE
Chat events mentions are always []

### ISSUE THREAD

**Issue by mortenn** [plugCubed/plugAPI#147]
It seems that the list of mentions isn't populated for chat events

**Comment by thedark1337** [comment]
The code to populate the mentions array is part of the parser for plugAPI's command handler, not the chat events.  I can see in eventObjectTypes that an empty array is always added. I'm not sure if I can but if its needed, I could try moving the code to populate the array outside of the command handler.

**Comment by mortenn** [comment]
I just presumed it would be populated as it was in the chat event object.
All I wanted to do was tag username objects in the log, so not a high priority thing on my behalf.

**Comment by mortenn** [comment]
Just a quick update on my perspective here:
Our bot processes chat from both discord and plug, so to enable the kind of things we are wanting to do, I will need to handle mentions outside of plugapi eventually anyway.

Due to this, I've already implemented this handling myself, so you can close this issue if you want :)
