### ISSUE TITLE
Duplicate advance event on skip (some times)

### ISSUE THREAD

**Issue by mortenn** [plugCubed/plugAPI#148]
I've not really been able to pin down how this happens, but we are seeing duplicate advances some times when a song is skipped.

**Comment by thedark1337** [comment]
From further discussion with @Dazzuh, this is a vanilla plug issue when a song skip happens at the same time an advance happens.

**Comment by mortenn** [comment]
Understood, I've put in a filter to eliminate the duplicates in the event flow in our bot
