### ISSUE TITLE
API not receiving events after initial login?

### ISSUE THREAD

**Issue by ronaldb** [plugCubed/plugAPI#59]
After last night's plug.dj update, the API doesn't seem to receive any events after logging in. My bot connects, the advance event fires to get the initial data (current DJ, dj list, lastPlay, media, startTime, etc.), and then nothing.

I assume something changed in the API interface with plug. The weird thing is plugCubed seems to receive all events no questions asked... But I don't see any changes in plugCubed other than the plug version updated.

Anyone else experiencing this?

**Comment by thedark1337** [comment]
Plug.dj "upgraded" their socket server and PlugAPI relies on that to connect to plug. Me and @TATDK  are trying to figure out how to connect again.

**Comment by ronaldb** [comment]
Thanks! If there's anything I can do to help, let me know.

**Comment by zirujauak** [comment]
I've been digging into this a bit since yesterday after losing my own bot implementation, and here's what I've figured out.  Hopefully it'll help:

1) plug.dj websocket URI has changed to wss://godj.plug.dj
2) The websocket connection request now requires a header "Origin: https://plug.dj" to be set
3) The websocket server now uses SSL
4) The websocket server no longer sends an 'o' event on open.  Once the socket is connected, send the auth message immediately
5) Incoming activity messages no longer has an 'a' prefix, just a single square bracket enclosure: [{"a":"action",...}]
6) Outgoing messages do not need to be wrapped in double-quotes, nor need to have contained double-quotes escaped: {"a":"chat",...}

**Comment by thedark1337** [comment]
1) yes that is correct
2) I set that and it now goes back and forth between error 1000 or error self signed cert.
3) SSL has always been used
4) I tested connecting to plug via the URL and it does send the auth code via the ws.on("open") code already in plugAPI but it doesn't join room....
5)http://screencast.com/t/jT6evVfSh47b The activity never actually changed (this is what it is now and it still matches plugAPI)
6) It is in JSON format as it should be

**Comment by zirujauak** [comment]
Are you still having connection errors?  The self-signed cert problem seems to be intermittent.  The other points aren't helpful if you can't get a stable WS connection opened.

**Comment by thedark1337** [comment]
Yes, the only changes i've made is to the socket URL and adding the origin to https://plug.dj. I'm now always getting socket 1000 (which essentially means get out)

**Comment by TATDK** [comment]
Please test and report back if 3.1.1 is fixing your issues

**Comment by AvatarKava** [comment]
30 mins uptime so far with no issues :+1:

**Comment by thedark1337** [comment]
http://screencast.com/t/8tjwG0vv I'm unsure if anyone else is having issues with commands but for me I can't use them. messageData.raw.type is undefined for me >_<

**Comment by zirujauak** [comment]
The new websocket server(s) have been really unstable for the past 24 hours, but that's nothing unusual following a plug update.  I've had plenty of issues simply connecting a user session on a browser and then not receive any events.

**Comment by ronaldb** [comment]
See the comment on #62 - plug may revert to old chat.

Also, events seem to fire, bot is chatting, but it's not responding to chat events in room?

**Comment by thedark1337** [comment]
are you running 3.1.2 ? message type had to be manually readded

**Comment by ronaldb** [comment]
Yep, running 3.1.2. I've removed the test on data !== 'h' in client.js, ws.on('message'), and the bot started responding. I've put the test back in, and now chats are ignored. As a matter of fact, we don't see the bot chat anymore...

I think the issue may be on the plug side. You may be on the right track with the chatsplit... but I thought they solved that many moons ago... :disappointed:

**Comment by thedark1337** [comment]
For now plug has reverted to the old socket. Please use npm install plugapi@3.1.0 if you're having issues connecting.

**Comment by thedark1337** [comment]
Plug has updated again, now its using the new socket. Update plugapi to latest and it should work. Going to close this issue for now seeing as it is working again.
