### ISSUE TITLE
Calm yourselves, gentlemen, you have some more time to develop

### ISSUE THREAD

**Issue by Tetheu98** [plugCubed/plugAPI#62]
Hey!

Just passing by to let you know that current issues that are connection and / or chat related will be fixed soon, for the old chat server will be coming back until developers can fix the new server's problems;
This means that any changes to adapt to the new server might be useless soon. Keep your eye out for the update! And have backups ;)

Thanks for being awesome!

Beta Tester
Brand Ambassador

**Comment by thedark1337** [comment]
Github allows us to revert back to the old socket easy with history and commit reverts. Yay for chat splits though /s  ;)

**Comment by TATDK** [comment]
A better way would probably be
npm install plugapi@3.1.0
