### ISSUE TITLE
CHAT_COMMAND

### ISSUE THREAD

**Issue by mcgrailm** [plugCubed/plugAPI#64]
plug api comes with CHAT_COMMAND event that triggers when someone types /<sometext> Could this be carried over to this api ?

**Comment by revanace** [comment]
The problem would be that the commands wouldnt be caught when a user doesnt have plug cubed running.

**Comment by mcgrailm** [comment]
Well i'm using the api right and people can type /foobar and all I want is to be able to get commands through the / command so they don't show up in the chat like they do when you use !foobar . By default Plugapi already does this I would like to see the event here as well is all I"m asking for.

**Comment by TATDK** [comment]
CHAT_COMMAND is clientside - this is not something plugAPI can catch
