### ISSUE TITLE
Chat Level Update

### ISSUE THREAD

**Issue by byzudo** [plugCubed/plugAPI#66]
I don't have time to make a PR, sorry.

```
22 Mar 19:12:27 [WARNING]  [plugAPI]  UNKNOWN MESSAGE FORMAT
 {
    "a": "roomMinChatLevelUpdate",
    "p": {
        "m": 2,
        "u": 4238154
    },
    "s": "someRoom"
}
```

I am proposing that `chatLevelUpdate` be added as an event. I would find this useful.

**Comment by thedark1337** [comment]
I shall look into this feature.

**Comment by thedark1337** [comment]
Please update to the latest plugAPI and let me know if it works as you wanted it to :+1:

**Comment by thedark1337** [comment]
I am closing this issue since it has been resolved.
