### ISSUE TITLE
roomJoin data argument is null

### ISSUE THREAD

**Issue by zudomc** [plugCubed/plugAPI#67]
When I have something like this:

```
bot.on("roomJoin", function(name, data) {
    console.log(data); // null
});
```

I see `null` printed to the console. Why?

**Comment by PlugLynn** [comment]
Because the roomJoin event only takes a name parameter:
https://github.com/plugCubed/plugAPI/blob/master/src/client.js#L746

(The wiki appears to be a bit out of date)

**Comment by zudomc** [comment]
Oh, OK. Didn't notice that. Is there any other way of get room data, like lock status?

**Comment by PlugLynn** [comment]
It doesn't seem so, unfortunately. Plug.dj has that information on the https://plug.dj/_/room/state endpoint, so you might be able to either hack it in yourself or to bug @TATDK about it :smile:

**Comment by zudomc** [comment]
@PlugLynn I'll PR it if I can be bothered.
