### ISSUE TITLE
User object contains severals undefined properties regarding the user targeted

### ISSUE THREAD

**Issue by Talos51** [plugCubed/plugAPI#68]
Hi ! First of all thanks for PlugAPI it's awesome !

Now the problem is that the user object contains numerous undefined properties when the user targeted is an other user than the bot itself. Here is a log of the 'chat' event : 
When the bot speaks here is the data object : 
```
chat-data{
	[raw] {
		[cid] => 3580020-1428000548856
		[message] => /me If you need help type !instructions
		[uid] => 3580020
		[un] => WatchPlug
		}
	[id] => 3580020-1428000548856
	[from] {
		[avatarID] => classic08
		[badge] => ea
		[blurb] => I'm WatchPlug, PvS Bot
		[ep] => 5817
		[gRole] => 0
		[grab] => false
		[id] => 3580020
		[ignores] => 
		[joined] => 2014-03-14 21:56:55.248000
		[language] => fr
		[level] => 5
		[notifications] => [object Object]
		[pVibes] => undefined
		[pw] => true
		[role] => 4
		[slug] => watchplug
		[status] => 0
		[username] => WatchPlug
		[vote] => 0
		[xp] => 1393
		[toString] => function (){return this.username}
		[addToWaitList] => function (){a.moderateAddDJ(this.id)}
		[removeFromWaitList] => function (){a.moderateRemoveDJ(this.id)}
		[moveInWaitList] => function (b){a.moderateMoveDJ(this.id,b)}
		}
	[message] => /me If you need help type !instructions
	[mentions] => 
	[muted] => false
	[type] => emote
}
```
Now when I'm speaking my user object contains undefined properties or 0 values ( i.e the exp ) : 
```
chat-data {
	[raw] {
		[cid] => 3579651-1428000570971
		[message] => !info(talos)
		[uid] => 3579651
		[un] => Talos51
		}
	[id] => 3579651-1428000570971
	[from] {
		[avatarID] => 80s10
		[badge] => style05
		[blurb] => undefined
		[ep] => undefined
		[gRole] => 0
		[grab] => false
		[id] => 3579651
		[ignores] => undefined
		[joined] => 2013-05-06 17:32:06.574000
		[language] => 
		[level] => 8
		[notifications] => undefined
		[pVibes] => undefined
		[pw] => undefined
		[role] => 5
		[slug] => undefined
		[status] => 0
		[username] => Talos51
		[vote] => 0
		[xp] => 0
		[toString] => function (){return this.username}
		[addToWaitList] => function (){a.moderateAddDJ(this.id)}
		[removeFromWaitList] => function (){a.moderateRemoveDJ(this.id)}
		[moveInWaitList] => function (b){a.moderateMoveDJ(this.id,b)}
		}
}
```
No matter what method is called ( getUsers(), getUser(my_id), data from various events) when this is an other user than the bot itself the user object throwed is populated with severals undefined.
There's something that i did wrong or this is a real issue ?
I'm running the latsest version of PlugAPI ( installed with *npm install -g plugapi --production*  every time i restart my VM for dev debug)

Thanks for reading me, and sorry for the mistakes that i could made, I'm French :smile:

**Comment by AvatarKava** [comment]
Some of the items (status, for example) have been deprecated/removed from plug so they will always come back as 0.

XP is not accessible to the API for other users (you can only get your own XP).

**Comment by Talos51** [comment]
Oh okay, yeah i've learned about status system removal, but even slug property is "personnal" ? it appears to be a little dumb that this property is private when it's purpose is to provide a link to your profile page ? :disappointed:

**Comment by PlugLynn** [comment]
The slug property isn't personal, but it's not included in every event. Particularly, userJoin events *do* have that property, but the slug property is **not** included in the initial room user data when you join a room. So it will exist on user objects that joined after you started your plugAPI app, but not on users who were already online.

**Comment by Talos51** [comment]
Allright, thanks for your responses, i'll use these to modify my bot.

Thanks !

**Comment by Talos51** [comment]
Sorry for double posting and the non-related question but I also need an other information : "did you know if running multiple instances of PlugAPI can cause problems?" because when i try to run my bot.js file for room1 & room2 the second instance is doing nothing, the logger didn't even display some PlugAPI version. the only trick i was able to find to run multiple instances of plugAPI was to install two plugAPI modules one in /usr/lib/nodejs_modules/ and another in /var/nodejs/mybot2/ so each bot.js script has it's plugAPI module.
And even when i try to restart each bot, blank logger, the only solution is to remove the cookie.tmp file in plugAPI directory ( i'm not sure about that ).

Thanks for futures replies.

**Comment by PlugLynn** [comment]
Yes, plugAPI uses a few global variables. That means that eg. the room object is shared across the entire module, so even if you create 10 plugAPI instances, they will all refer to the same room object. Indeed if you install the module twice, they will each have their own room object, so I would expect that would help. However, it isn't officially supported by any means.

I'd think, if you have two completely separate directories like this:

* bot1/
  * node_modules/
    * plugapi/
  * bot.js
* bot2/
  * node_modules/
    * plugapi/
  * bot.js

That should work. The `cookie.tmp` files end up in the `bot1` and `bot2` directories, so they should be completely separate. I can't say for sure though.

**Comment by thedark1337** [comment]
That is correct, if you have a bot in separate directories, they will not share any of the data between each other. If you require multiple bots, what @PlugLynn  said needs to be done :+1:

**Comment by Talos51** [comment]
Ok thanks that's what i've done for my bots : 
* /usr/lib/nodejs/ ( with symlink to /usr/lib/node_modules )
  * mybot1/
    - mybot.js

* /var/nodejs/mybot2/
  - node_modules/
    * plugapi/
  - mybot2.js

(Maybe my cookie.tmp problem was because i mixed the used accounts across the two directories )
Thanks for your replies and sorry for all these questions!
