### ISSUE TITLE
New Bots Will not connect

### ISSUE THREAD

**Issue by mcgrailm** [plugCubed/plugAPI#69]
I have a bot that I've been running for some time now. A friend asked if i could make her one. I created a new account for the bot and am able to login without a hitch. However when I use the my bot code and the new creds it hangs. I've tried using the basic bot exmaple and still have the same issue.  Please help

var PlugAPI = require('plugapi');
// console.log(PlugAPI) // this works
// nothing happening here
var bot = new PlugAPI({
		"email": "email.address@yahoo.com",
		"password": "password"
});
bot.connect('mixxx-s-fun-house-1'); // The part after https://plug.dj

bot.on('roomJoin', function(room) {
    console.log("Joined " + room);
});

bot.on('userJoin', function(data) {
    console.log(data);  // this does happen
});

**Comment by thedark1337** [comment]
Is there any error that shows up in the console? Ex: Incorrect credentials, server error, something like that? 

I usually have issues connecting when plug's servers are being slow or unresponsive or my server is having connection issues.

**Comment by mcgrailm** [comment]
Nope , no errors it just hangs, and then if I change the account information it takes a little longer than usual to connect but does.

**Comment by foodbandlt** [comment]
I actually had issues with this when I first made my bot for Connect the Songs.  The only way that I could get it to work reliably is to give the PlugAPI constructor a callback and assign the event handlers inside of it.

```
this.API = new plugapi({
		"email": settings.user,
		"password": settings.pass
	}, function(bot){
		that.botInst = bot;
		bot.setCommandPrefix(settings.commandPref);
		that.connectBot(); // Wrapper for bot.connect()
		
		bot.on("advance", function(data){
			if (data.currentDJ != null){
				escorter.escort();
				scrobbler.scrobble(data);
			}
			
			if (data.lastPlay.dj == null || data.currentDJ == null)
				return;
			that.API.woot();
		});
	});
```

**Comment by thedark1337** [comment]
Try deleting the cookies.tmp in node_modules/plugapi and see if that helps. That's the session cache.plugAPI uses. Hmm so it hangs and never logs in? Which plugAPI version are you using?

**Comment by mcgrailm** [comment]
Ok that fixed the problme @thedark1337, thank you. So now I need to figure out how I can have more than one bot on the server at a time because of this cache thing is making that imposible

**Comment by mcgrailm** [comment]
ohh and I'm Running plugAPI v.3.1.2

**Comment by AvatarKava** [comment]
@mcgrailm you'd need two installs of plugAPI in separate directories - there need to be two instances so you can have two copies of cookies.tmp.

**Comment by mcgrailm** [comment]
haha I can see where that would work but that is not at all how it should be. Maybe one of us can figure out how to mod cookie.js to account for more than once instance at a time

**Comment by thedark1337** [comment]
What happens on login is plugAPI utilizes a temporary file cache for the bot's login info so that later on it can login with that cookie.tmp, thus why it runs only one bot at a time.

As @AvatarKava  said, you'd need to have a modular directory like

bot1 -> node_modules -> plugapi

bot2 -> node_modules -> plugapi

and have separate code for each one, unless someone has a better way to cache the cookie data that will be the only way to do things.

Is there any other issues you need help with?

**Comment by mcgrailm** [comment]
Well if there is some way that the temp file could be associated with a the bots id  so that the temp file is written and called as <bot_id>_cookie.tmp or if they can be all stored in the cache.tmp file in a similar manner that would cool. But for the original question I have a work around though not the most ideal

**Comment by thedark1337** [comment]
We'll look into that issue and see if it can be resolved.
