### ISSUE TITLE
Explain?

### ISSUE THREAD

**Issue by SkipppSkippp** [plugCubed/plugAPI#70]
Can someone explain how to actually get npm install? I usually know how to do thing like this, but I just dont understand this..

**Comment by PlugLynn** [comment]
`npm` ships with node.js, which is an open source JavaScript software development platform. You can get it here: https://nodejs.org/

**Comment by thedark1337** [comment]
@SkipppSkippp Has your question been answered ?

**Comment by thedark1337** [comment]
Seeing as there are no further comments I am closing this issue. Please reopen if you need anymore help.
