### ISSUE TITLE
Chat API

### ISSUE THREAD

**Issue by stopbox** [plugCubed/plugAPI#76]
I have not seen any chat api for deleting chat

**Comment by anjanms** [comment]
bot.moderateDeleteChat('<chat id>');
https://github.com/plugCubed/plugAPI/blob/master/src/client.js#L2058

**Comment by thedark1337** [comment]
Most of plugAPI's API is the same as plug's, except we add a callback function so you can call a method after another. 

We have not documented all of our API, but most of it can be found here: https://github.com/plugCubed/plugAPI/wiki


Example:

```javascript

//browser
API.moderateDeleteChat(cid);;

//plugAPI
bot.moderateDeleteChat(cid);

//Callback Example

bot.moderateDeleteChat(cid, function() {
   console.log('Message Deleted');
});
```

**Comment by stopbox** [comment]
When i have the time i will help update the documentation and thank you
