### ISSUE TITLE
getPlaylists not returning an array

### ISSUE THREAD

**Issue by purechaose** [plugCubed/plugAPI#77]
In the documentation for getPlaylists([callback]) in client.js, it says it returns the array, and it's implementation is like that used in other functions (like grab([callback])), where the assumption is that bufferObject's get([callback]) returns the data stored in it, but as far as I can tell, get() only returns undefined. This breaks client's grab, getPlaylist, getPlaylisy (partially), getActivePlaylist, and several other functions that use the previously mentioned functions. 

I'd make a PR like last time, but I'm not sure whether you want to access the array stored in bufferUtil via callback or return.

**Comment by thedark1337** [comment]
I am testing the functionality and it seems to be returning an array fine for me.

``` javascript
bot.getPlaylists(function(data) {
    console.log(data);
});
```

http://screencast.com/t/7ZPkgyibW

Are you sure that the account has playlists?

**Comment by yonip** [comment]
That does work, and i do use it to search through the playlists for the one I want, but 
```javascript
PlugAPI.prototype.getActivePlaylist = function() {
    var playlistsData = playlists.get();
    for (var i in playlistsData) {
        if (!playlistsData.hasOwnProperty(i)) continue;
        if (playlistsData[i].active) {
            return playlistsData[i];
        }
    }
    return null;
};
```
does not, which is my major problem, since that means grab doesn't work, and I am pretty certain it's because this line
```javascript
var playlistsData = playlists.get();
```
leaves playlistData as null since 
```javascript
playlist.get()
```
passes the array to the callback function, rather than returning it from the function.

**Comment by thedark1337** [comment]
The latest version, 3.3.0 should work. The API has changed slightly to add in callbacks for some of the  

Example:

```javascript
bot.on('command:grab', function(data) {
    //if (!settings.tflbot) return;
    if (data.havePermission(PlugAPI.ROOM_ROLE.BOUNCER)) {
        bot.grab(function() {
            bot.sendChat('Added Current Song to playlist');
        });
    }
});
```

```javascript
bot.getActivePlaylist (function(playlist) {
    console.log(playlist);
});

```

```javascript
        bot.getPlaylists(function(playlists) {
            console.log('Playlists:' + require('util').inspect(playlists));
        });

```

etc.

Please let me know if your issue has been fixed :+1:

**Comment by yonip** [comment]
Sorry for the late response, but this did fix the issue. Thank you!

**Comment by thedark1337** [comment]
no problem.
