### ISSUE TITLE
Retrieve Room object or Meta property

### ISSUE THREAD

**Issue by Talos51** [plugCubed/plugAPI#80]
Hi!

I tried to figure it out but found nothing atm. Is there a way to retrieve the room object (ie. some bot.getRoom() ). Few methods can get Room properties like Users,Waitlist,Media, ... But I would like to be able to retrieve the entire Room object or be able to get only "Room.meta" that contains (name, slug, welcome, etc... ).

Tried severals things like bot.room / room.getRoomMeta / etc... but always end in undefined variables :cry: 
There are setters as Room.Name, Room.Description, Room.Welcome but no getters ? Too bad !

Thanks !

EDIT1: getRoomstate() may be useful?
EDIT2: After a second look the getRoomState() it's private so back to square one.

EDIT3: So many edits sorry ^^ but it seems that the booth object is in the same situation no bot-accessible getters (ie. to know lock status, cycleStatus )

**Comment by Talos51** [comment]
My bad, there's getRoomState() method, didn't notice it. As usual PlugAPI > all :smile:

**Comment by thedark1337** [comment]
Ill look into this issue as soon as I can

**Comment by Talos51** [comment]
Thanks, I think it's more a request/feature than a real issue insofar methods aleady exists and just need to be accessible by a bot instance (remove @private or make public getter/setter) to extend the possibilities to retrieve/manage information of booth and room.

**Comment by thedark1337** [comment]
Added a lot of new methods in that commit, thanks to @anjanms  for the contribution. Please let me know if there are any issues :+1:
