### ISSUE TITLE
LOGIN ERROR: Can't get CSRF Token

### ISSUE THREAD

**Issue by johnRivs** [plugCubed/plugAPI#82]
Happened shortly after I saw a message saying 'maintenance'.

**Comment by AvatarKava** [comment]
https://plug.dj - Plug's in maintenance mode right now, which will prevent anyone (bots included!) from logging in.

**Comment by thedark1337** [comment]
https://www.facebook.com/plugdj/posts/953058441425423

Plug will be in maintenance for the rest of the day for upgrades.

**Comment by johnRivs** [comment]
Thanks very much!
