### ISSUE TITLE
User status

### ISSUE THREAD

**Issue by CookieMichal** [plugCubed/plugAPI#84]
Hello,
just wanted to say that those functions seems useless now.
```javascript
PlugAPI.prototype.getStatus
```
```javascript
PlugAPI.prototype.setStatus
```
`getStatus` always returns 0 and `setStatus` returns `[REST Error] [SyntaxError: Unexpected token <]` since it sends request to no longer existing endpoint that returns 

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>

```

**Comment by AvatarKava** [comment]
Being able to set user status was removed a while ago in the actual plug app (you used to be able to set active/away/gaming/at work/etc).  They've left the get method in the API for backwards compatibility, but it will always return 0.
