### ISSUE TITLE
Unknown message format

### ISSUE THREAD

**Issue by Loscillo** [plugCubed/plugAPI#85]
When a moderator ban an user, I get this message : 

```
21 Jun 20:15:27 [WARNING]  [plugAPI]  UNKNOWN MESSAGE FORMAT
 {
    "a": "modBan",
    "p": {
        "m": "As2piK",
        "mi": 4282601,
        "t": "MC_盧moo",
        "d": "f"
    },
    "s": "as2pik-2"
}
```

**Comment by thedark1337** [comment]
Unknown Message Format is when we don't log or handle one of plug's events. Those can be ignored. Unless someone wants me to add a notification in the console for bans.

**Comment by Loscillo** [comment]
In the wiki, modBan is an event, so you can't remove the "unknown message format" for this ?

**Comment by thedark1337** [comment]
https://github.com/plugCubed/plugAPI/blob/master/src/client.js#L877

I can add it to the list of events plugAPI does not need to handle or log when I get the time.

**Comment by prostagma** [comment]
Would a `console.log('Function Deprecated')` help in this case ?
