### ISSUE TITLE
Self Skip Method

### ISSUE THREAD

**Issue by Talos51** [plugCubed/plugAPI#86]
Hi there!

I just thought that could be nice to give access to the "Booth/Skip/Me" endpoint that could simplify some homemade "bot.selfskip" mehods and this would trigger the appropriate event ("%username% has decided to skip his turn" instead of "%Bot% skipped current dj" ).

from official API : 
```
//USER_SKIP
This is triggered when the current DJ skips their own turn. It passes the user name of the DJ who skipped.
//USAGE
API.on(API.USER_SKIP, listener);
```

Thanks!

*Info*:
* Endpoint: https://plug.dj/_/booth/skip/me
* Method: POST
* Returns: Usual HTTP returns

Maybe something like this ?
```javascript
  var endpoints = {
   // ...
    SKIP_ME: 'booth/skip/me',
   // ...
  };

//noinspection JSUnusedGlobalSymbols
/**
 * Self Skip
 * @param {RESTCallback} [callback] Callback function
 * @returns {Boolean} If the REST request got queued
 */
PlugAPI.prototype.SelfSkip = function(callback) {
    if (!room.getRoomMeta().slug || room.getDJ() === null || !room.isDJ()) {
        return false;
    }

    queueREST('POST', endpoints.SKIP_ME, undefined, callback);
    return true;
};
```

**Comment by Talos51** [comment]
Added a possible implementation of that function.

**Comment by thedark1337** [comment]
:+1:  thanks, I'll add it in soon

**Comment by Talos51** [comment]
Just a message to avoid making a new issue because it would be pointless. 

Could it be possible to add ``` PLAYLIST_CYCLE: 'playlistCycle', ``` event to plugAPI ignoring list ? because it currently triggers the "unknow message format" info log. 

Thanks

**Comment by thedark1337** [comment]
Yes that is entirely possible, I am currently working on a rewrite of plugAPI's methods to fit NodeJS's callback style of callback(err, data) atm and will add that in as well

**Comment by Talos51** [comment]
Ok Thanks !

**Comment by thedark1337** [comment]
Added your requested features.  @Talos51  :+1:

**Comment by Talos51** [comment]
Great Job Thanks :+1:  ! I'll try this asap

**Comment by thedark1337** [comment]
Awesome, please let me know if you need anything else added, otherwise close this issue :+1:
