### ISSUE TITLE
Add DJ-Cycle-Method

### ISSUE THREAD

**Issue by Fuechschen** [plugCubed/plugAPI#88]
The Javascript-Api of PlugDJ itself is providing an method called "moderateDJCycle()" with a parameter given as boolean for the djcycle. would it be possible to make this method also usable in plugapi?

**Comment by thedark1337** [comment]
https://github.com/plugCubed/plugAPI/blob/master/src/client.js#L2398

We already have it as changeDJCycle. :+1:

**Comment by Fuechschen** [comment]
sorry, i haven't found this method in the wiki...

**Comment by thedark1337** [comment]
Its fine, those docs haven't been updated in a while

**Comment by Talos51** [comment]
Yes, tried some time ago to keep the wiki up to date by editing and adding methods but, it seems that I've forgot to add changeDJCycle. I'll try to add that one and update wiki pages if I got free time.

**Comment by thedark1337** [comment]
:+1:  Thank you
