### ISSUE TITLE
Did moderateForceSkip stop working?

### ISSUE THREAD

**Issue by johnRivs** [plugCubed/plugAPI#91]
I'm using a manager account to do `moderateForceSkip()` but it doesn't skip the song. However, it executes the callback I pass into said function.

Did the endpoint change maybe?

**Comment by thedark1337** [comment]
Does any error show up in the console you run the bot from?

The only change i've made to moderateForceSkip is to self skip if the bot is the dj.

**Comment by avatarkava** [comment]
Also make sure the person you're attempting to skip isn't of a higher rank.

**Comment by johnRivs** [comment]
It doesn't show anything in the logs.

It's trying to skip a regular user.

**Comment by johnRivs** [comment]
Downgraded to 3.3.0 and it works.

**Comment by Talos51** [comment]
Yes it seems that we're not longer able to skip other people than the bot itself since 3.5.0 ( 3.3.0 was able to skip even higher ranks )

Will try to look to [source code](https://github.com/plugCubed/plugAPI/blob/master/lib/client.js#L2143) to maybe figure out why.

**Comment by goto-bus-stop** [comment]
Possibly an issue with `room.isDJ`?

**Comment by Talos51** [comment]
Whoa nice ! I didn't even noticed that ( ) are missing from isDJ function, Monday is definitely a bad day to start working ^^

**Comment by johnRivs** [comment]
Nice :O

Hopefully your PR gets accepted soon™.

**Comment by Talos51** [comment]
I think it will be updated very soon ( by today imho ) cause it's just some missing () .

**Comment by Talos51** [comment]
Thanks Dark !

**Comment by thedark1337** [comment]
if you're getting errors like name not resolved or anything DNS related it is due to people hacking DNS Servers, change to something like Google DNS or OpenDNS if you are.

I am currently working on the v4 release of PlugAPI. Testing things out first to try and weed out bugs

**Comment by johnRivs** [comment]
Dark, have you considered multiple bot instances running in v4? https://github.com/atomjack/plugbotapi does it with phantomjs.

**Comment by thedark1337** [comment]
It should be possible without it now since i removed the cookies.tmp requirement

**Comment by johnRivs** [comment]
Oh I haven't tried yet. Up until this point I was forking processes to have multiple bots, but it takes up so much memory :(

**Comment by Talos51** [comment]
I'm back, yes first it was some DNS issues even with my OpenNIC DNS servers, but I had the feeling that plug.dj himself was also slow ( latency in chat, slow request when deleting message, etc... ). But now everything seems to work fine, we're able to skip other people including higher rank again.

Thanks.
