### ISSUE TITLE
TypeError: Cannot call method 'send' of null

### ISSUE THREAD

**Issue by byzudo** [plugCubed/plugAPI#95]
When launching a bot, (code below), this happens. Any ideas on how to fix this?

![Error in console](https://i.gyazo.com/ee30e0116d8de9807145c3f77a675a2b.png)

    var PlugAPI = require("plugapi");

    var bot = new PlugAPI({
        email:"***",
        password:"***"
    });

    bot.connect("***");
    bot.sendChat("/me ZudoBot enabled!")

**Comment by thedark1337** [comment]
I see the issue, next version will fix it

**Comment by thedark1337** [comment]
Issue should be resolved now, please let me know if it isn't :+1:
