### ISSUE TITLE
I keep getting this error?

### ISSUE THREAD

**Issue by xSidewinderx** [plugCubed/plugAPI#96]
module.js:485
    throw err;
          ^
SyntaxError: /home/sidewinder/Desktop/node_modules/request/node_modules/mime-types/node_modules/mime-db/db.json: Unexpected token a
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:482:27)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/sidewinder/Desktop/node_modules/request/node_modules/mime-types/node_modules/mime-db/index.js:11:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
sidewinder@sidewinder-All-Series:~/Desktop/Chat$

**Comment by thedark1337** [comment]
can i see the full error? That just means it threw an error but I'm unsure from where

**Comment by xSidewinderx** [comment]
Updated

**Comment by thedark1337** [comment]
Appears somewhere in your code OR plugAPI's requests threw an error somewhere in the process, but its strange the stack trace doesn't specify where...

**Comment by xSidewinderx** [comment]
Thats just it, my code is the same. Never threw that error. I stopped it cause I was done for abit, came back that  showed up.

**Comment by thedark1337** [comment]
May I see what your code looks like if you don't mind?

**Comment by xSidewinderx** [comment]
var PlugAPI = require('plugapi');
var readline = require('readline');
var colors = require('colors');
path = require('path')
var config = require(path.resolve(__dirname, 'config.json'));

var bot = new PlugAPI({
    "email": "EMAILREMOVED",
    "password": "PASSWORDREMOVED"

});
var rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
  terminal: false
});


bot.connect('the-byte');
bot.on('roomJoin', function(room){
    console.log("Joined " + room+" As User: "+ bot.getUser().username);
    
    //Enabling Bot Talk
    rl.on('line', function(line){
        bot.sendChat(line);
    });

    //Chat
    bot.on('chat',mainChat);
      function mainChat(data){
      date = new Date();
      timeString = '<'.gray + date.getHours() + ':'.gray + date.getMinutes() + ':'.gray + date.getSeconds() + '>'.gray;
      console.log(timeString+(data.raw.un).green+': '+(data.message).cyan);
    }
});


bot.on('userJoin', function (data) {
       console.log('[Join]', 'User Joined: ' + data.username);
      // bot.sendChat('Welcome ' + data.username);
   });
bot.on('userLeave', function (data) {
        console.log('[LEAVE]', 'User left: ' + data.username);
   });

**Comment by thedark1337** [comment]
With this code: https://ghostbin.com/paste/wy9cg it is working fine for me. I switched colors to [https://npmjs.com/package/chalk](Chalk) , because overloading prototypes with colors is not my style. I've also made it login from config and it seems to be working fine with plugAPI 4.2.0

I'm still unsure how that error got thrown, maybe the module didn't install correctly ?

**Comment by xSidewinderx** [comment]
Got my stuff to work, just moved my code into a new foler, than reinstalled plugapi with npm

**Comment by thedark1337** [comment]
Good to hear :+1: , I added an example for commands in my code snippet as well if you want to see it.

**Comment by xSidewinderx** [comment]
I could take a look, but this code im working on now is for chat-logging purpose. :P

**Comment by thedark1337** [comment]
ah I see, nevermind then :P Have fun! , feel free to email me if you have any questions.
