### ISSUE TITLE
When a guest leaves, the API says the bot does instead?

### ISSUE THREAD

**Issue by ImGrumpy** [plugCubed/plugAPI#97]
When a guest user joins, userJoin data shows this:

```
{
    "avatarID": "base05",
    "role": 0,
    "id": 12590082,
    "guest": true
}
```

When that same guest leaves, userLeave shows this:
```
{
    "avatarID": "rock14",
    "badge": "rockset-g",
    "gRole": 0,
    "grab": false,
    "id": 3942480,
    "ignores": [],
    "joined": "2013-12-13 03:57:43.388000",
    "language": "en",
    "level": 16,
    "notifications": [],
    "pp": 591692,
    "pw": true,
    "role": 3,
    "slug": "lil-buddy",
    "status": 1,
    "sub": 0,
    "username": "Lil*Buddy",
    "vote": 1,
    "xp": 124604
}
```

Lil*Buddy is our bot's name.  He's not actually leaving.  I can duplicate this over and over, I'm sure it's the guest that's triggering this.

**Comment by Talos51** [comment]
that's maybe because a guest is not a real user and he's defined by some undefined/null values, so if the code has been wrote in the way that if undefined/null user is passed it's the bot itself that it's choosen we end up in this situation. That needs a look at the code.

**Comment by thedark1337** [comment]
looking into the issue atm, might've found it. Will be fixed in next patch release

**Comment by thedark1337** [comment]
Next released version (not sure when) will have this issue resolved.

User Object will be:

```
 { id: 0, guest: true}
```
if a guest leaves in the new version
