### ISSUE TITLE
PlugAPI cannot remove messages... again?

### ISSUE THREAD

**Issue by Talos51** [plugCubed/plugAPI#98]
Hi,

I think last update broke again the delete message system ? I updated my bot to last version yesterday and now I'm running into an issue where I can't delete the function messages (ie. !uptime ) when messages where sent by an equal or higher rank.
It was working like a charm before updating to last version. And it sounds like some previous issues.
The point is I can't figure if it's plug.dj or plugAPI.

Thanks.

**Comment by thedark1337** [comment]
I've updated it to work exactly like the browser API in which same rank or higher rank chat can't be deleted. I will however add in an option to disable this functionality , once i figure out a good name for it.

**Comment by Benzi** [comment]
@Talos51 use version `4.1.2` as a temporary measure until Alex fixes his shit :eyes:

**Comment by thedark1337** [comment]
Oi you, don't call it shit. I'm welcome to suggestions to what to name the variable >_>

**Comment by anjanms** [comment]
bot.ignoreChatRole, bot.moderateIgnoreChatRole, bot.moderateHigherRoleChat, bot.moderateAllChat

**Comment by thedark1337** [comment]
moderateAllChat sounds good, anything else as a suggestion ? :smile:

**Comment by Talos51** [comment]
Something around "ignore*Role" sounds great if you can bypass role in other functions than chat moderation, but if it's only for moderateChat the "moderateAllChat" sounds good. But as I always say "You're coding, you're choosing" ^^

**Comment by thedark1337** [comment]
As plug is going to come back eventually this year or next (I am not 100% sure), I have begun work on plugAPI again. I have added the option `bot.deleteAllChat` to 4.2.1
